### ISSUE TITLE
Adapt rate from ball filter to match the vision rate

### ISSUE THREAD

**Issue by jaagut** [bit-bots/bitbots_world_model#18]

**Comment by jaagut** [comment]
The vision runs at 100 Hz (or 130Hz with bit-bots/bitbots_vision/pull/289), but will output balls at max. 65 Hz (as we get only 65 FPS from the camera).
At which rate should the ball filter run?

Should we run at 65+ Hz to handle every incoming ball? In that case, should we also overclock it (see bit-bots/bitbots_vision/pull/289) to reduce delay?
Should we run at lower rates to reduce cpu usage?

**Comment by NFiedler** [comment]
Honestly, I think we need to evaluate this by testing.
